# 장기 기억 정확도 비교 막대 차트 (예시 데이터)
#@ chart bars
#@ title 장기 기억 정확도 (예시 데이터)
#@ unit %
#@ series 기억 붙임, 기억 없음
#@ bar 단일 세션 사실: 91.4 60.2
#@ bar 여러 세션 종합: 79.7 44.1
#@ bar 시간 추론: 85.0 -
#@ bar 지식 갱신: 88.5 70.3
