# 기억을 붙이기 전과 후의 작업당 토큰 화살표 차트 (예시 데이터)
#@ chart arrows
#@ title 기억을 붙이면 작업당 토큰이 준다 (예시 데이터)
#@ unit 토큰
#@ scale log
#@ arrow 코딩 에이전트 A: 120000 -> 31000
#@ arrow 코딩 에이전트 B: 95000 -> 28000
#@ arrow 편집기 도우미: 60000 -> 21000
#@ arrow 사내 에이전트: 8000 -> 5200
